### ISSUE TITLE
Cloning simulating results in disappearance of 'urine fraction extreted' 

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/PK-Sim#99] opened 2017-04-11 09:13 UTC
After cloning a simulation including 'simulated drug-plasma concentration' and 'fraction of drug in urine', the fraction of drug in urine is not visible anymore, nor is it selectable in the chart-editor of the cloned-simulation.

[Urine_fraction_not_visible.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/912673/Urine_fraction_not_visible.zip)

**Comment by msevestre** [comment] 2017-04-11 16:26
I can reproduce the issue

**Comment by msevestre** [comment] 2017-04-11 17:14
Well this is because the `fraction excreted` observer has been renamed to `fraction excreted to urine` in 6.2 or 6.3. 
As such `fraction excreted` does not exist in new simulations (or cloned simulations) and the output is not found.
Suggestion is to select `fraction excreted to urine` in the clone. Then everything will work as expected, even when cloning the clone.

Let me know if this is an acceptable solution for you
@Yuri05 Closing the issue for now as I don't think we should introduce any conversion steps for this minor issue

**Closed by msevestre** 2017-04-11 17:14 UTC
Labels: effort: low (hours), prio: high

**Comment by Incei** [comment] 2017-04-12 06:53
This is acceptable for me. Thank you.
