### ISSUE TITLE
Define "Organism|Volume (plasma)" with a sum formula

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#531] opened 2018-01-15 14:49 UTC
If #530 will be implemented, the parameter "Organism|Volume (plasma)" should be defined with a tag formula, as it is done for "Weight of blood organs".

**Comment by Yuri05** [comment] 2018-08-21 14:26
Duplicate of #572

**Closed by Yuri05** 2018-08-21 14:26 UTC
Labels: type: feature
