### ISSUE TITLE
Ontogeny factor in Expression Profile?

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/PK-Sim#2532] opened 2022-12-14 14:58 UTC
Should this parameter be part of Expression Profile Building Block

**Comment by PavelBal** [comment] 2023-02-28 15:03
@Yuri05 Could you help us out specifying what has to be done?

**Comment by msevestre** [comment] 2023-05-24 15:03
After discussion today, here is the initial plan

## Expression Profile

We will add two new parameters: 
* Ontogeny factor GI Table
* Ontogeny factor Table

with the corresponding ontogeny table.

**Comment by msevestre** [comment] 2023-06-02 14:44
ok this is a duplicate of #2626

**Comment by msevestre** [comment] 2023-06-02 14:44
starting on this

**Comment by msevestre** [comment] 2023-06-15 17:02
@PavelBal @Yuri05 
This is proving to be VERY challenging. I have spent two full days on this and I am nowhere done. We need to discuss what we want exactly and why because right now, I am opening a massive can of worms 

The main problem that I have is about reusability and consistency. 
At the moment, I have the table in the expression profile. This works. But in the individual, we need to have a parameter as a function of PMA and this table in the expression. This works also but when we want to export to mobi, we have this weird mismatch: We do not want the ontogeny factor in the expression profile because it references age of the individual. But we do not want the parameter in the individual either because it references a specific expression profile.

Not sure how to deal with this best

**Comment by msevestre** [comment] 2023-06-15 21:09
For now, I have added the paramter to the expression profile....To be continued

**Comment by msevestre** [comment] 2023-06-15 21:13
@Yuri05 @PavelBal 
What about ontogeny factor albumin and glycoprotein. Those two could also be implemented the same way (and exported as table + arg, but this time in the individual. Thoughts?)

**Comment by PavelBal** [comment] 2023-06-16 13:00
> What about ontogeny factor albumin and glycoprotein. Those two could also be implemented the same way (and exported as table + arg, but this time in the individual. Thoughts?)

I think this also makes sense.

**Comment by Yuri05** [comment] 2023-06-20 10:56
> What about ontogeny factor albumin and glycoprotein. Those two could also be implemented the same way (and exported as table + arg, but this time in the individual. Thoughts?)

makes sense :)

**Closed** 2023-06-23 15:08 UTC
Labels: type: task
