### ISSUE TITLE
Almost impossible to drag data into a simulation plot

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/PK-Sim#98] opened 2017-04-11 08:32 UTC
It is almost impossible to drag data into a simulation plot for visualisation. 4 out of 5 times the drag fails.

[data_drag_issue - Copy.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/912561/data_drag_issue.-.Copy.zip)

**Comment by msevestre** [comment] 2017-04-11 15:33
@Incei I cannot reproduce the issue. It is as good (or as bad) as it was before.
On which machine are you trying the drag and drop?

**Comment by msevestre** [comment] 2017-04-11 15:33
@Yuri05 What is the environment used for testing 7.1?

**Comment by Incei** [comment] 2017-04-11 15:34
TDELEVC0115

**Comment by Incei** [comment] 2017-04-11 15:35
It happened for each test that I performed

**Comment by Yuri05** [comment] 2017-04-11 15:38
>What is the environment used for testing 7.1?

Windows Server 2008 R2 SP1 
64bit

**Comment by rwmcintosh** [comment] 2017-04-11 15:42
Are you installing in a VM on that server? or directly on server OS?

**Comment by Yuri05** [comment] 2017-04-11 15:42
directly on server

**Comment by msevestre** [comment] 2017-04-11 15:48
Can you reproduce when installing on a local machine as opposed to using a
server?

**Comment by rwmcintosh** [comment] 2017-04-11 22:05
After a series of tests today I can offer that the situation seems to be related to remote desktop.
When remoting into Windows Server 2008 drag/drop observed data is barely usable, remote desktop with Windows 10 seems somewhat better, but not as good as with using the hardware directly.

**Comment by msevestre** [comment] 2017-04-12 00:02
A workaround would be to add a context menu option to add the selected
observed data (single or multiple) into the active plot of the active
simulation?

**Comment by Yuri05** [comment] 2017-04-12 08:33
>A workaround would be to add a context menu option to add the selected observed data (single or multiple) into the active plot of the active simulation?

Yes, that would be fine

**Comment by Incei** [comment] 2017-04-12 09:04
I agree

**Comment by msevestre** [comment] 2017-04-12 12:51
Closed in favor of #104

**Closed by msevestre** 2017-04-12 12:51 UTC
Labels: subsystem: charts, type: bug
