### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xuyichao0732** [Open-Systems-Pharmacology/PK-Sim#2694] opened 2023-08-04 02:19 UTC
Application:
PK-Sim® 11.2.142

Value cannot be null.
Parameter name: source

Stack trace:
```
at System.Linq.OrderedEnumerable`2..ctor(IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer, Boolean descending)
   at System.Linq.Enumerable.OrderBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at PKSim.Core.Mappers.ProtocolToSchemaItemsMapper.MapFrom(Protocol protocol)
   at PKSim.Presentation.Presenters.Simulations.GlobalPKAnalysisPresenter.<CanCalculateGlobalPK>b__33_0(Compound compound)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PKSim.Presentation.Presenters.Simulations.GlobalPKAnalysisPresenter.CanCalculateGlobalPK()
   at PKSim.Presentation.Presenters.Simulations.PopulationPKAnalysisPresenter.CalculatePKAnalyses(IPopulationDataCollector populationDataCollector, ChartData`2 timeProfileChartData, PopulationStatisticalAnalysis populationAnalysis)
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.calculatePKAnalysis()
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.RefreshData()
   at PKSim.Presentation.Presenters.Charts.EditPopulationAnalysisChartPresenter`3.UpdateAnalysisBasedOn(IPopulationDataCollector populationDataCollector)
   at PKSim.Presentation.Presenters.Charts.EditPopulationAnalysisChartPresenter`3.UpdateAnalysisBasedOn(IAnalysable analysable)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.<UpdateResultsInCharts>b__23_0(ISimulationAnalysisPresenter presenter)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.UpdateResultsInCharts()
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Handle(SimulationResultsUpdatedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

**Comment by Yuri05** [comment] 2024-03-01 13:49
duplicate of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2632
will be fixed in the next release

**Closed by Yuri05** 2024-03-01 13:49 UTC
Labels: type: bug
