### ISSUE TITLE
Metabolic chain: too many modifiers

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2708] opened 2023-08-18 09:23 UTC
E.g. load Itraconazole template (which will automatically load all metabolites), create an Individual with CYP3A4 and create a simulation using all compounds. [WrongModifiers.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/12377739/WrongModifiers.zip)

This will create the metabolic network:
`Itraconazole ➡️ Hydroxy-Itraconazole➡️ Keto-Itraconazole➡️ N-desalkyl-Itraconazole ➡️N-desalkyl-Itraconazole-CYP3A4-xy Metabolite`

Each reaction should have only CYP3A4 as modifier. However, it has also several compounds added as modifiers, e.g.
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/48c2e0e4-458f-4178-a19e-41b23d7690ad)

**This does not impact the simulation results.**
However the reaction diagram looks like 💩 

![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/837d8c73-8a8e-4771-8a5d-baf8828fe108)

**Comment by Yuri05** [comment] 2023-08-18 09:32
I created the same metabolic network with dummy compounds:
C1➡️C2➡️C3➡️C4➡️C4-CYP3A4-Metabolite
And here it looks correct. No wrongly added modifiers
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/ed1a2848-9f4d-4168-8e15-552eaa0695fb)

**Comment by msevestre** [comment] 2023-09-07 01:05
This has something to do with interactions

**Comment by msevestre** [comment] 2023-09-07 01:07
So I think this is correct
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/6e55c95a-38fc-4e55-af7b-f0a9ad8c79cd)

You have defined an interaction for CYP3A4 for all molecules. Therefore, each reaction where CYP3A4 is a modifier will also be modified indirectly by the interaction process

**Comment by msevestre** [comment] 2023-09-07 01:10
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/b46c47db-827f-4853-9692-7eb14877f6fd)

This is explicitly implemented so

**Comment by msevestre** [comment] 2023-09-07 01:11
According to me, this is by design. Closing. Please reopen if I am missing the point

**Closed by msevestre** 2023-09-07 01:11 UTC
Labels: type: bug

**Comment by Yuri05** [comment] 2023-09-07 09:01
Well, **in general** it is wrong, I think. E.g. imagine the situation:
* compound **C** is metabolized to **C-metabolite** by **CYP**
* **CYP** is inhibited by the Inhibitor **I**
* in some model container: 
  * **C**, **C-metabolite** and **CYP** are present
  * Inhibitor **I** is NOT present

Then the metabolization reaction `C==>C-metabolite` will not be created in this container because the inhibitor is not there - which is wrong.

This scenario is not possible in PK-Sim. It could only happen if you export a simulation to MoBi and then e.g. set Inhibitor to "IsPresent=false" in a container. 

Pretty unlikely scenario though, so I would not change the behaviour now.
I guess the only reason for adding inhibitors as modifiers is to show in the reaction diagram, that the reaction is influenced by an inhibitor.
So maybe we should extend a modifier with a flag "OPTIONAL". For optional modifiers, reaction can take place if they are not available. 
But not V12 for sure :)

**Comment by Yuri05** [comment] 2023-09-07 09:04
ok, forget it.
it will become even much more complicated, because in absence of an inhibitor we have completely different reaction rate.
would be extremely complicated to implement and not worth the effort.
