### ISSUE TITLE
Crash when cancelling import in PKSim

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/PK-Sim#1790] opened 2021-06-15 20:35 UTC
@msevestre commented on [Tue Jun 15 2021](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1089)

Using the latest core (June 15th)

Start PKSim,
Import
Change some stuff (Species etc)
Click on the X

Application:
PK-Sim® 10.0.0

Value cannot be null.
Parameter name: key

Stack trace:
```
at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Core.Domain.Project.AddImporterConfiguration(ImporterConfiguration configurationToAdd)
   at OSPSuite.Core.Commands.AddImporterConfigurationToProjectCommand.ExecuteWith(IOSPSuiteExecutionContext context)
   at OSPSuite.Core.Commands.OSPSuiteCommand`1.Execute(TContext context)
   at OSPSuite.Core.Commands.Core.CommandExtensions.Run[T,ExecutionContext](T commandToExecute, ExecutionContext context)
   at OSPSuite.Core.Domain.Services.ObservedDataTask.AddImporterConfigurationToProject(ImporterConfiguration configuration)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.addObservedData(Func`1 importConfiguration, Compound compound, Boolean allowCompoundNameEdit) in C:\projects\PK-Sim\src\PKSim.Infrastructure\Services\ImportObservedDataTask.cs:line 232
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataToProjectForCompound(Compound compound) in C:\projects\PK-Sim\src\PKSim.Infrastructure\Services\ImportObservedDataTask.cs:line 137
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataToProject() in C:\projects\PK-Sim\src\PKSim.Infrastructure\Services\ImportObservedDataTask.cs:line 62
   at PKSim.Presentation.UICommands.ImportConcentrationDataCommand.Execute() in C:\projects\PK-Sim\src\PKSim.Presentation\UICommands\ImportConcentrationDataCommand.cs:line 17
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment] 2021-06-18 13:54
duplicate of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1794

**Comment by abdelr** [comment] 2021-06-25 07:12
closing in favor of #1794

**Closed by abdelr** 2021-06-25 07:12 UTC
