### ISSUE TITLE
for multiple LLOQ values, the smallest should be used and displayed in simulations, etc.

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/PK-Sim#2416] opened 2022-11-09 09:36 UTC
Currently, when uploading an observed data set that contains multiple LLOQ values, it seems that the largest value is used and displayed in the simulations. Per definition (LOWER limit of quantification!), the lowest of the LLOQ values should be used and displayed.

**Comment by Yuri05** [comment] 2022-11-09 10:44
duplicate of https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1524

**Closed by Yuri05** 2022-11-09 10:44 UTC

**Comment by Yuri05** [comment] 2022-11-09 10:45
duplicate of https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1524
