### ISSUE TITLE
Number of cells/g tissue missing for monkey and minipig

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/PK-Sim#1488] opened 2020-05-21 20:32 UTC
For total hepatic clearance processes (in vitro hepatocytes), the "Number of cells/g tissue" is missing for monkey and minipig.
Is this a bug or is no value reported (in literature)?

Same for "microsomal protein/g liver" in the "in vitro liver microsomes" processes (monkey, minipig and mouse).

**Comment by msevestre** [comment] 2020-05-22 00:06
no value reported (at least not according to the DB)

**Comment by Yuri05** [comment] 2020-05-22 17:11
Duplicate of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1427?

**Comment by StephanSchaller** [comment] 2020-05-22 17:20
> Duplicate of #1427?

Half of it, true, #1427 covers microsomal protein, but PK-Sim also needs an update for #cells/g Liver for monkey and minipig

**Comment by StephanSchaller** [comment] 2020-06-02 10:18
So, is it the same issue for the cells/g liver, that we had values in V7.3 but these got lost for V8?

We now have a list with literature sources we can provide...

**Comment by msevestre** [comment] 2020-06-02 13:47
>So, is it the same issue for the cells/g liver, that we had values in V7.3 but these got lost for V8?

eh? Nothing was lost between versions. I have no idea how you can infer this conclusion from the #1427 thread lol

**Comment by StephanSchaller** [comment] 2020-06-02 13:59
Yeah, yeah... I mis-read the reply from J-Herz... these were hi own values...

Anyway, how would you want the values for this thread/topic provided?

**Comment by msevestre** [comment] 2020-06-26 14:55
Table? Then we can update the DB:)

**Comment by StephanSchaller** [comment] 2023-02-28 06:26
[Hepatocellularity V1.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10847159/Hepatocellularity.V1.zip)

Is this usable?

**Comment by msevestre** [comment] 2023-03-29 23:32
also misssing for cattle

**Comment by msevestre** [comment] 2023-03-29 23:33
@StephanSchaller Is there a reference for this value?

**Closed** 2023-03-29 23:42 UTC
Labels: type: feature, up for grabs

**Comment by StephanSchaller** [comment] 2024-08-07 10:43
@Yuri05 , @msevestre , we can take this. Can you assigne Rob, Ben or Pavel in the next Dev Meeting
