### ISSUE TITLE
Refresh of Related Items list missing

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/PK-Sim#1018] opened 2018-11-22 16:22 UTC
After enlarging the Related Items list in the Journal view by moving the separation bar upwards, the Related Items list is not refreshed. Hiding and fixing the Journal view does not help nor resizing the PK-Sim window.
![grafik](https://user-images.githubusercontent.com/25579536/48914240-183f7480-ee7b-11e8-90a4-7c6910fb03d6.png)

**Comment by UlrichSi** [comment] 2018-11-26 14:42
The refresh problem is affecting quite a number of actions done with the WJ. In particular, PK-Sim test case 4.37.2, Step 8: After deleting 1 of 3 WJ pages, 2 (!) pages appear to be deleted. The page not explicitly deleted will reappear after manual refresh by close/open window.

**Comment by msevestre** [comment] 2018-11-26 14:53
This is all so weird because we did not change anything between 7.3 and 7.4 in the working journal.

**Comment by UlrichSi** [comment] 2018-11-26 14:56
Maybe something was changed behind your back, like some library or included tool? Somewhat disturbing, I agree.

Adding tags in the WJ editor window will also require closing and re-opening the WJ listing window to have it updated.

**Comment by msevestre** [comment] 2018-11-26 15:08
Are you testing on a real latptop or a vm?

**Comment by msevestre** [comment] 2018-11-26 15:09
And you can confirm it was not there on 7.3?

**Comment by msevestre** [comment] 2018-11-26 15:12
because I can't reproduce using 7.4 on my machine...
![image](https://user-images.githubusercontent.com/1041237/49022814-c68d3780-f163-11e8-8085-468cc92b0b67.png)

**Comment by msevestre** [comment] 2018-11-26 15:16
ACtually the issue is that the window is too small (width) . The height is adjusting automatically, but a slider is shown to navigate from left to right 
What about you make the journal view wider?

**Comment by msevestre** [comment] 2018-11-26 15:18
e.g.
![image](https://user-images.githubusercontent.com/1041237/49023145-81b5d080-f164-11e8-86c7-5bec4135fb47.png)

Making the window bigger
![image](https://user-images.githubusercontent.com/1041237/49023159-8b3f3880-f164-11e8-9271-cf0987274b03.png)

**Comment by msevestre** [comment] 2018-11-26 15:20
@ju-rgen @UlrichSi 
We could also have the related item view fill up the whole space if this is preferred?

**Comment by UlrichSi** [comment] 2018-11-26 15:23
I am using v 7.4 on a remote server - the one that has the nightly build installed. No VM, no laptop.

In 7.3, the refresh problem with tags added in the edit window is also present here. The refresh issue with the deleted page is not present.

Filling up the whole space with related items might work out for @ju-rgen since he is a multi-screen aficionado. I am not sure if I would like to have it.

**Comment by UlrichSi** [comment] 2018-11-26 15:41
@msevestre I will do more tests tomorrow and see that I clarify your questions.

**Comment by UlrichSi** [comment] 2018-11-27 09:53
In my setting, the "delete issue" only happens when the WJ edit window is open with any page; deletion is done via the context menu of the page listing.

The tag issue seems to be some problem with WJ page saving on closing the edit window. I cannot reproduce it today.

**Comment by msevestre** [comment] 2018-11-27 13:46
@UlrichSi I can't reproduce the delete issue either. At any rate this has nothing to do with the issue at hand.
If you can reproduce, consistently, please create another issue and we'll look at it. At the moment, just too hard to reproduce

**Closed by msevestre** 2018-11-27 13:46 UTC
Labels: subsystem: UI
