### ISSUE TITLE
Error to save a model

### ISSUE THREAD

**Issue by eva-comsopolita** [Open-Systems-Pharmacology/PK-Sim#1432] opened 2020-02-14 19:59 UTC
I try to save my model. I select File > Save > Save As and save modeling with a short name, but after closed everithing i cant open again.

What thats wrong?

**This is the Clipboard**

Application:
PK-Sim® 8.0.22

SQL logic error
no such table: SUMMARY_CHART

Stack trace:
```
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at OSPSuite.Core.Extensions.DbConnectionExtensions.ExecuteNonQuery(IDbConnection sqlLite, String query)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.migrateTo5_3(SQLiteConnection sqlite)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.MigrateSchema(String fileFullPath)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(ICoreWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass16_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.openProjectFromFile(String projectFile, Boolean shouldStartWorker)
   at PKSim.Presentation.Services.ProjectTask.Run(StartOptions startOptions)
   at PKSim.Presentation.Presenters.Main.PKSimMainViewPresenter.Run()
   at PKSim.UI.Views.Shell.<OnLoad>b__4_0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment] 2020-02-14 20:11
It seems that saving the file was not successful. Can you reproduce that behavior all the time or is this a one time off?

e.g. open pksim. add an individual. Save 
Reopen, save as, reopen. Does htis work?

**Comment by eva-comsopolita** [comment] 2020-02-14 20:18
Hello and thanks for answering.

If I save this file and try to open it, I get an error every time I tried.

But if I open a file that I have downloaded from open-system, it works for me and opens without any problem.

**Comment by msevestre** [comment] 2020-02-14 20:21
@eva-comsopolita Just to be clear
If you create a NEW file and try to save it and open it again, it does not work, ever?

**Comment by msevestre** [comment] 2020-02-14 20:22
@eva-comsopolita can you try with MoBi?

**Comment by eva-comsopolita** [comment] 2020-02-14 20:36
Yes, If I Create a NEW file and try to save it and open it again, it does not work, ever?

I will try with MoBi

**Comment by eva-comsopolita** [comment] 2020-02-14 20:39
It may not have explained me well.

How is the normal process to save in Pk-sim?
Clicking on File-Save As, just let me save with ".pksim5" format

I use a windows laptop.

**Comment by msevestre** [comment] 2020-02-14 20:40
pksim5 is the pksim file format.

What file are you trying to open?

**Comment by eva-comsopolita** [comment] 2020-02-14 20:41
I save the file in pksim 5, so I try to open the same file from pksim application.

**Comment by msevestre** [comment] 2020-02-14 20:48
Yes this is the way to go. 

So you are not able to save any files at all correct?

Can you also do a save as to one of the file from github that you downlaoded? e.g. download the file, save as and open it

Also are you savign the file on a network drive ? If yes, can you try to save on your desktop and seeif this works?

**Comment by eva-comsopolita** [comment] 2020-02-14 21:01
If I try to open a downloaded one and try to save it with another name it gives me the same error and I cannot open it.
I'm setting it up on the desk and it doesn't work either.
I do not understand that it can fail.

**Comment by msevestre** [comment] 2020-02-14 21:13
well someone is wrong with your installation as you do not seem to be able to save any files.
Did you install the software using the setup ? OR are you using the portable version?

Can you try to do the same with Mobi? it is usign the same technology under the hood so I am wodnering if this is an error due to pksim or a general problem with your laptop

**Comment by eva-comsopolita** [comment] 2020-02-14 22:16
Thanks for the help, in the end what I have done has been to save on the original file, that I could.

As you say I think the problem is due to the installation.  Since I can save on an already created file, but I cannot create a new one and save it.  I see that saving should also create a json file, but when I save it is only created in pksim format.  The installation was through a portable version that my teacher passed me, I imagine that I would not install it well and that is why it does not work.

**Comment by eva-comsopolita** [comment] 2020-02-14 22:17
Thanks for everything, I finished what I wanted to do today as I could.  But you will try to delete it and reinstall the application.

**Comment by msevestre** [comment] 2020-02-19 22:23
@eva-comsopolita Can you let us know if you managed to fix the issue?

**Comment by msevestre** [comment] 2020-02-26 22:28
Closing. Please reopen if you still have issues after  a fresh install

**Closed by msevestre** 2020-02-26 22:28 UTC
