### ISSUE TITLE
PK-Sim crashes when importing larger datasets

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/PK-Sim#862] opened 2018-06-27 09:23 UTC
I tried to import a datafile (excel or csv). 7578 lines (390 individual concentration time profiles).

Bug report attached.
[pk-simbug.txt](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2140560/pk-simbug.txt)

**Comment by sfrechen** [comment] 2018-06-27 12:38
Splitting into two datasets worked...

**Comment by msevestre** [comment] 2018-06-27 12:43
@sfrechen the crash report in text file does not mention anything about importer at all.

Can you attach the excel file here? (or send it to me via email)
When does the crash happen? Loading the file, after mapping, trying to transfer back to PK-Sim?

**Comment by sfrechen** [comment] 2018-06-27 12:58
I cannot attach or send the data (confidential).

The crash happens after mapping and clicking the "Import" button. PK-Sim seems to work for quite a while and then crashes. Tried it a couple of time (also restarting windows).

**Comment by msevestre** [comment] 2018-06-27 13:06
@sfrechen If we cannot reproduce the bug, we cannot fix it. Suggestion would be to change the source file by randomizing the values somehow so that we can have a look at it.

**Comment by sfrechen** [comment] 2018-06-28 14:34
Please find attached.
[Data.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2145696/Data.xlsx)

**Comment by msevestre** [comment] 2018-06-28 15:24
@sfrechen awesome.

**Comment by Yuri05** [comment] 2019-02-21 15:44
Still an issue in 7.4. Not a memory problem but prob. just too many graphical objects created (Importer tries to create 390 tabs for preview).

@msevestre We could reduce max. number of preview Tabs to avoid this (e.g. 50 or 100).

@sfrechen Workaround for now: increase windows limits for GDI/User objects
 * start `Regedit` as administrator
 * navigate to **HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows**
 * increase value of **GDIProcessHandleQuota** (e.g. double it; max. value is _65536_ (**decimal**))
 * increase value of **USERProcessHandleQuota** (e.g. double it; max. value is _65536_ (**decimal**))
 * restart the computer

**Comment by Yuri05** [comment] 2023-03-15 15:59
Seems to be not a problem in 11.1 anymore. Import takes like 1 second. closing

**Closed by Yuri05** 2023-03-15 15:59 UTC
Labels: type: bug
