### ISSUE TITLE
PK-Analysis for Projects created in versions 8 or 7 is incomplete shown in 9.1

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#1554] opened 2020-09-03 09:15 UTC
Here it is like the PK-Analysis looks for a Simulation last opened in e.g. V8.1 (project was created in Version 7.2):
![image](https://user-images.githubusercontent.com/25585248/92094974-5d753200-edd5-11ea-9f25-58c4f73af4c5.png)
 If I open the same file in 9.1
some calculated parameters like AUC_tDlast-1_tDlast are Missing  
![image](https://user-images.githubusercontent.com/25585248/92095176-9d3c1980-edd5-11ea-8ac4-3263ab0d44cb.png)
cloning or reconfiguring of the Simulation does not help.

However when I create the simulation new from scratch using the same BB the parameters will show up:
![image](https://user-images.githubusercontent.com/25585248/92095619-2d7a5e80-edd6-11ea-918c-f996fa312643.png)

Is that normal behavior?
Would be good if one could open older version in 9.1 and the same PK-analysis results are shown.

Best, Tobias

**Comment by Yuri05** [comment] 2024-12-27 15:47
Asuming the issue is obsolete. Closing.

**Closed by Yuri05** 2024-12-27 15:47 UTC
