### ISSUE TITLE
After change in compound file by adding a clearance or removing and replace I have frequently this bug.

### ISSUE THREAD

**Issue by hanssmit777** [Open-Systems-Pharmacology/PK-Sim#2884] opened 2024-03-22 07:44 UTC
Application:
PK-Sim® 11.2.142

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Core.Domain.SimulationQuantitySelection.Clone()
   at OSPSuite.Core.Domain.OutputMapping.Clone()
   at OSPSuite.Core.Domain.OutputMappings.<>c.<UpdatePropertiesFrom>b__1_0(OutputMapping x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at OSPSuite.Core.Domain.OutputMappings.UpdatePropertiesFrom(IUpdatable source, ICloneManager cloneManager)
   at PKSim.Core.Model.Simulation.UpdatePropertiesFrom(IUpdatable sourceObject, ICloneManager cloneManager)
   at OSPSuite.Core.Domain.Services.CloneManagerStrategy.Clone[T](T objectToClone)
   at PKSim.Core.Services.Cloner.createClone[T](T objectToClone, ICloneManager cloneManager)
   at PKSim.Core.Services.Cloner.CloneForModel[T](T objectToClone)
   at PKSim.Presentation.Presenters.Simulations.ConfigureSimulationPresenterBase`1.createSimulationToConfigureBasedOn()
   at PKSim.Presentation.Presenters.Simulations.ConfigureSimulationPresenterBase`1.configureSimulation(Simulation simulation, ISubPresenterItem subPresenterItem, Action actionToPerformBeforeDisplayingView)
   at PKSim.Presentation.Presenters.Simulations.ConfigureSimulationPresenterBase`1.ConfigureSimulationWithBuildingBlock(Simulation simulation, IPKSimBuildingBlock templateBuildingBlock)
   at PKSim.Presentation.Services.ConfigureSimulationTask.<>c__DisplayClass9_0.<Configure>b__0(IConfigureSimulationPresenter x)
   at PKSim.Presentation.Services.ConfigureSimulationTask.configure(Simulation simulationToConfigure, Func`2 configureAction)
   at PKSim.Presentation.Services.ConfigureSimulationTask.Configure(Simulation simulationToConfigure, IPKSimBuildingBlock buildingBlockToActivate)
   at PKSim.Presentation.Services.SimulationTask.UpdateUsedBuildingBlockInSimulation[TBuildingBlock](TBuildingBlock templateBuildingBlock, UsedBuildingBlock usedBuildingBlock, Simulation simulation)
   at PKSim.Presentation.UICommands.UpdateBuildingBlockInSimulationUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment] 2024-03-22 09:57
Can you please provide a more detailed workflow and also attach an example project (if possible)?

**Comment by hanssmit777** [comment] 2024-03-22 11:34
Hello Juri. Sure will do so
I have done a full install validation after installing osp.

Kind regards
Hans

I will reply from my work email, see cc

Op vr 22 mrt 2024 10:57 schreef Juri Solodenko ***@***.***>:

**Comment by Yuri05** [comment] 2024-03-22 13:32
If you want to upload any attachments to your upcoming answer: please do it directly on GitHub.
(when answering via email, attachments get lost)

**Comment by hanssmit777** [comment] 2024-03-22 13:35
Will do

Op vr 22 mrt 2024 14:33 schreef Juri Solodenko ***@***.***>:

**Comment by hanssmit777** [comment] 2024-03-22 14:26
sorry for the confusion, the added PKSIM feedback was from simulation on a larger file, more compound files and more dog data..

**Comment by Yuri05** [comment] 2024-03-25 17:35
I cannot reproduce. Is it possible to upload a project where you face the problem?

**Comment by hanssmit777** [comment] 2024-03-26 23:02
Just ran in similar error today.
I will have to anonamise the file and share it tomorrow.


Op ma 25 mrt 2024 18:35 schreef Juri Solodenko ***@***.***>:

**Comment by msevestre** [comment] 2024-07-16 14:59
@hanssmit777 Any info here please?

**Comment by rwmcintosh** [comment] 2024-10-11 09:06
No doubt related to https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2988, which has been investigated and has a root cause identified.

Closing in favour of #2988

**Closed by rwmcintosh** 2024-10-11 09:06 UTC
Labels: type: bug, feedback required
