### ISSUE TITLE
Feature: Advanced protocol for user-defined applications

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/PK-Sim#1070] opened 2019-01-17 06:51 UTC
A feature to allow definition of an advanced protocol for user-defined applications (e.g. to allow multiple dose simulations with intervals >OnceDaily for SC dosed mAbs).

**Comment by LkKov** [comment] 2019-03-29 17:52
Hello everybody!
Is this still an issue wich is going to be tackled? Since I am also highly interested in using the advanced protocol for user-defined application to allow specific multiple dosing regimens.
This would be really helpful!

Thank you very much in advance!
Best regards,
Lukas

**Comment by msevestre** [comment] 2019-04-16 13:03
Is a duplicate of #1170

**Closed by msevestre** 2019-04-16 13:03 UTC
Labels: duplicate, type: feature
