### ISSUE TITLE
UI: Create individual -> Individual parameters are hidden if CKD disease state is selected

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2277] opened 2022-08-02 08:11 UTC
With "Healthy":

![image](https://user-images.githubusercontent.com/25903040/182325841-16d0cc92-5101-4864-b09d-25cb17e4e2e9.png)

With "CKD":

![image](https://user-images.githubusercontent.com/25903040/182325911-680c23bb-e84f-4298-81c4-91bafc0112a9.png)

**Comment by msevestre** [comment] 2022-08-04 21:44
Can you try and let me know. Works for me on 250% scaling

**Comment by PavelBal** [comment] 2022-08-08 08:23
"Value origin" is not there:

![image](https://user-images.githubusercontent.com/25903040/183373624-e88eb087-45b3-434c-9cde-3453d85406af.png)

**Comment by msevestre** [comment] 2022-08-08 14:03
This is so annoying. Same stuff as before. we will have to experiment

**Comment by Yuri05** [comment] 2022-12-27 15:59
seems to be fixed. @PavelBal please reopen if not

**Comment by PavelBal** [comment] 2023-01-09 13:32
"Value origin" is now not shown with and without CKD :D

**Comment by msevestre** [comment] 2023-01-09 13:38
Well I don't have a solution for you. I am giving up on this. @rwmcintosh has a 4k and can fix it. Impossible to fix a bug that you can't reproduce

**Comment by Yuri05** [comment] 2023-01-10 17:43
Fixed by https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/2506

**Closed** 2023-01-10 18:10 UTC
Labels: type: bug, subsystem: UI
