### ISSUE TITLE
Subfolder for building blocks

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2037] opened 2022-01-11 11:48 UTC
It would be great to have subfolders for the building blocks in the BB-explorer. At least for the administration protocols, where the protocols could be grouped by study or applied molecule.

**Comment by Yuri05** [comment] 2022-01-11 15:22
duplicate of #1435

**Comment by Yuri05** [comment] 2022-08-04 08:17
Closing in favor of #2242

**Closed by Yuri05** 2022-08-04 08:17 UTC
Labels: type: feature
