### ISSUE TITLE
Parameter Identification: Transfer to Simulation applies relative factor multiple times

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#893] opened 2018-07-25 07:48 UTC
To reproduce, use a project with simulation and parameter identification task, then open the PI task.
1. In the Parameters tab, check the box "Use as Factor" for any of the varied parameters, then adjust the range.
2. Run the parameter identification. When finished, click on the Results tab.
3. Click on "Transfer to simulation".
4. Right-click the building block of the simulation with the corresponding fitted parameter (e.g., "Molecule" for "Lipophilicity"). Select "Show differences" and verify that the new parameter has been calculated correctly by multiplying the original value with the factor from PI.
5. Repeat steps 3 and 4.

Result: The PI Factor has been applied twice.
The expected behavior would be that the absolute value of the PI run is applied, there is no sense in repeatedly applying the factor to the current value.

**Comment by PavelBal** [comment] 2018-07-26 07:34
Yes, I once reported this "feature" and also consider it a "bug".

**Comment by UlrichSi** [comment] 2018-07-26 07:36
@PavelBal You are the only one who thinks of it as feature. ;-)
If you reported this in Github, could you please set a link?

**Comment by PavelBal** [comment] 2018-07-26 07:40
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/156

I think it was the very first issue I opened in GitHub :)

**Comment by UlrichSi** [comment] 2018-07-26 07:43
> I think it was the very first issue I opened in GitHub :)

No wonder nobody remembers it here... thanks for the update!

**Comment by Yuri05** [comment] 2021-08-11 11:32
duplicate of #156

**Closed by Yuri05** 2021-08-11 11:32 UTC
Labels: type: bug, risky, subsystem: PI & SA
