### ISSUE TITLE
7.3 beta: Difference for unused solubility is shown

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/PK-Sim#662] opened 2018-05-03 08:19 UTC
Attached file: While building simulation “Sol_Tab_1”, the solubility “Table” was selected. 
If the value for the alternative solubility “SingleCalc” is changed in the compound building block, the red traffic light symbol appears at the simulation “Sol_Tab_1” indicating a difference to the building block which is actually not present since “SingleCalc”  is not used in the simulation. 
This is confusing and not consistent with the behaviour of other parameters.
[ph_Sol.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1970066/ph_Sol.zip)

**Comment by msevestre** [comment] 2018-05-03 17:52
done

**Comment by Christoph27** [comment] 2018-05-18 11:44
Still present in version 7.3.0.22 beta of PK-Sim

**Comment by msevestre** [comment] 2018-05-18 12:32
@Christoph27 I can't reproduce 
I have tried with an old project and a brand new project. If I changed the value of SingleCalc, the simulation that DOES not use SingleCalc remains green.

Please describe exactly how to reproduce the issue

**Comment by Christoph27** [comment] 2018-05-18 12:52
Cf. Attached project "Test_phSol_2018_05_18" generated with version 7.3.0.22 beta (portable version). It contains a simulation “Sim_CalcProf” using solubility “Measurement” and “Sim_Table” using solubility “Table_1”.

With 7.3.0.22 beta (portable version):
At the Compounds Building Block: Change value of solubility “Meassurement” from 0.3 mg/l to 0.5 mg/l. Then the red traffic light appears also at the simulation “Sim_Table” for which solubility “Measurement” is not used.  

[Test_phSol_2018_05_18.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2016916/Test_phSol_2018_05_18.zip)

**Comment by msevestre** [comment] 2018-05-18 13:27
>This is not consistent with the behaviour of other parameters.

I disagree. As soon as an alternative is used in ANY simulation, changing the alternative will change other simulations. However, if one alternative is not used, you can change it how often you want and it won't affect other simulations.

That's why it works in your original ph_sol project when i tested because you have only one simulation

you can try the same with lipophilicity  LIPO1 and LIPO2 and 2 simulations using LIPO1 and LIPO2 respectively. The behavior is the same.
As such the behavior is consistent with other parameters. 

Please let me know if you agree. CLosing for now

**Closed by msevestre** 2018-05-18 13:27 UTC
Labels: type: bug, unable to reproduce

**Comment by Christoph27** [comment] 2018-05-18 13:59
I think that behaviour is not reasonable even if it occurs for all parameters: A certain change in the Compounds Building Block will turn a simulation red or leave it green depending on which other simulations are present. I would expect that a simulation remains green if the change in the building block does not affect the simulation.

**Comment by msevestre** [comment] 2018-05-18 14:03
Ok. But this is not a new behavior and has nothing to do with the new solubility table parameter. 

May I suggest to create a new feature request for that? 

In all honesty, this is a very hard problem to solve but who knows... we might have some fantastic idea how to solve this

**Comment by Christoph27** [comment] 2018-05-18 14:06
OK
