### ISSUE TITLE
After export from PK-Sim, some "Property" parameters are in the PSV-BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2113] opened 2022-03-04 14:00 UTC
After exporting a PK-Sim model with expressed proteins, following parameters that are "Property" are created in the PSV-BB:

- Fraction expressed in blood cells membrane
- Fraction expressed on tissue-side membrane of vascular endothelium

What for? @msevestre It is a bug, don't you think?

**Comment by msevestre** [comment] 2022-03-09 17:15
This will be resolved with usage of ContainerCriteria for Parameters in Molecule

**Comment by msevestre** [comment] 2022-03-15 16:57
Fraction expressed in blood cells membrane  is NaN just because it's a formula and the tag are defined with MOLECULE instead of ..

**Comment by msevestre** [comment] 2022-03-15 16:59
oh I see. They should not be created because they are property

**Closed** 2022-03-17 08:51 UTC

**Comment by RobinM92** [comment] 2022-04-09 12:32
Hello, 
I was wondering if this issue is the cause of unwanted behavior of relative expression when sending a simulation from pksim to mobi. E.g. in https://github.com/Open-Systems-Pharmacology/Forum/discussions/1151 I sent asimulation using relative expression of EGFR to MoBi, and all the relative expression values are attributed to intracellular expression in the tissues (probably due how it is coded connected to the interstitial expression). For now, the only work-around I have found is adding all relative expression values per tissue (in ISF, plasma and blood cells) manually, which is extremely cumbersome and errorprone. Of course this is relevant as we use rel. expression in the turnover reactions of receptors per tissue, if not they all converge to the same concentration...
