### ISSUE TITLE
GIT transit time can be included in user defined variability

### ISSUE THREAD

**Issue by regulus92** [Open-Systems-Pharmacology/PK-Sim#1247] opened 2019-05-14 03:11 UTC
In an individual simulation, gastric emptying time and small intestine transit time are modified to 41.5 min and 10 h, respectively. But when creating a population, distribution of small intestine transit time is still around the initial value. And I find that it can not be set in user defined variability. I think it should be an important parameter for oral absorption.
![QQ图片20190514110629](https://user-images.githubusercontent.com/45459593/57668129-e85a7800-7638-11e9-92f6-cb685d398341.png)
![QQ图片20190514110652](https://user-images.githubusercontent.com/45459593/57668140-ee505900-7638-11e9-9995-985a2ac88616.png)
![QQ图片20190514110721](https://user-images.githubusercontent.com/45459593/57668146-f14b4980-7638-11e9-82f4-7814e870f02c.png)

**Comment by Yuri05** [comment] 2020-02-10 11:14
Cannot reproduce in PK-Sim 8.0.
Distribution of GIT / SITT in a created POP are around **modified** values.
Closing for now. @regulus92 Please reopen if you still face the issue in PK-Sim 8.0.

**Closed by Yuri05** 2020-02-10 11:14 UTC
