### ISSUE TITLE
Time stamp changes by simply opening and closing a file

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/PK-Sim#410] opened 2017-10-19 12:10 UTC
This is minor but irritating:

When I open a PKSim file and close it without saving, the time stamp for the file ("Änderungsdatum" in german) in Windows Explorer still updates to current Time/Date.
Is this on purpose?

**Comment by msevestre** [comment] 2017-10-19 12:25
@StephanSchaller 
That should not happen unless the file you are trying to open is quite old and a database conversion needs to happen underneath the hood. This is a rare case however

I just tried with a few projects and I cannot reproduce the behavior

While file is open
![image](https://user-images.githubusercontent.com/1041237/31770642-e524cfaa-b4a6-11e7-85a4-8afe03df149e.png)

Once PKSim is closed
![image](https://user-images.githubusercontent.com/1041237/31770672-fc2bea8a-b4a6-11e7-9a88-01992508542c.png)

As you can see, nothing happened to the file

**Comment by StephanSchaller** [comment] 2017-11-09 22:46
Will get back to you.

**Comment by UlrichSi** [comment] 2017-11-21 12:03
I just experienced a case where, after conversion from a model created with PK-Sim 5.2.1, the original project file was overwritten when just opening it (i.e., w/o doing a "Save"). The behavior is reproducible.

**Comment by StephanSchaller** [comment] 2017-11-21 20:36
Now, I have files to reproduce this.
How can I upload files other that GIF, JPEG, PNG,...?

**Comment by msevestre** [comment] 2017-11-22 02:19
@UlrichSi A 5.2.1 project will require a database update that happens automatically at the moment. As such the project is overwritten indeed (actually database updated but data are unchanged)

Last time the database was updated was a long time ago so this should not happen with any new ish project (6.2 +)

@StephanSchaller 
Zip the files

**Comment by Yuri05** [comment] 2018-08-21 15:04
Should be fixed meanwhile . Closing. Please reopen if still an issue

**Closed by Yuri05** 2018-08-21 15:04 UTC
Labels: question, unable to reproduce
