### ISSUE TITLE
Expression profile lost after scaling individual

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1724] opened 2021-04-28 10:08 UTC
Using the current build of v10, large parts of the expression profile of an individual is lost when scaling to another individual. E.g. when scaling from ICRP to Asian, only the following expression value is kept - all other organs/compartments are kicked out:
![image](https://user-images.githubusercontent.com/26541603/116386667-4aa6e600-a81a-11eb-95e0-ebbb8bc030ac.png)

**Comment by Incei** [comment] 2021-04-28 14:23
I can confirm the same bug when scaling to a child

**Comment by Incei** [comment] 2021-04-29 12:50
btw, when exporting to snapshot, and loading back again in pk-sim, all other organs/compartments are back again, however all are 0.

**Comment by msevestre** [comment] 2021-04-29 12:52
Thanks @Incei 
I managed to reproduce. The issue is the scale function indeed. It will be fixed today

**Closed** 2021-05-04 16:55 UTC
Labels: type: bug
