### ISSUE TITLE
Define Volume Plasma as Sum parameter

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#572] opened 2018-02-19 16:06 UTC
Similar to what was implemented with Weight, the parameter volume plasma should be defined as a Sum Parameter

**Comment by msevestre** [comment] 2018-02-19 16:06
@Yuri05 Any reason why this was not done during previous refactoring?

**Comment by Yuri05** [comment] 2018-02-19 16:27
Time

**Comment by msevestre** [comment] 2019-11-30 21:50
@Yuri05 This is done right? Closing. Please reopen if not

**Comment by Yuri05** [comment] 2019-12-05 10:04
nope, still a TODO

**Comment by Yuri05** [comment] 2021-08-11 10:56
duplicate of #2

**Closed by Yuri05** 2021-08-11 10:56 UTC
Labels: type: feature
