### ISSUE TITLE
When creating a new compound Value origin for pKa is filled

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/PK-Sim#1011] opened 2018-11-21 13:22 UTC
Publication-Toxicol ..... is a wrong default, isn't it?
![grafik](https://user-images.githubusercontent.com/25579536/48843898-ba3a6080-ed98-11e8-8e8a-e5118f26c8f0.png)

**Comment by msevestre** [comment] 2018-11-21 13:30
@yuri05. I'd say so!! DB changed lately?

**Comment by Yuri05** [comment] 2018-11-21 14:17
>DB changed lately?

Apparently yes. Might be a bug during DB conversion 7.3=>7.4
In any case, default value origin must be empty here.

**Comment by Yuri05** [comment] 2018-11-21 14:29
>~Apparently yes. Might be a bug during DB conversion 7.3=>7.4~

Ok, it's not a DB problem.
The Problem is in [CompoundTypeGroupPresenter.cs#L92](https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/a974f21b56f514927b2365f9ea522e26fb250a01/src/PKSim.Presentation/Presenters/Compounds/CompoundTypeGroupPresenter.cs#L92)

Value origin is taken from some hidden parameter of the **COMPOUND_PKA**-group (where it is defined indeed).
`_editValueOriginPresenter.Edit` should be called with the first **_visible_** parameter.

**Comment by msevestre** [comment] 2018-11-21 14:52
Yes working on it. 
Actually it should be taken from the first compound_type parameter. (pka or compound type). that's all

**Comment by msevestre** [comment] 2018-11-21 23:29
Fixed with #1012

**Closed by msevestre** 2018-11-21 23:29 UTC
Labels: prio: high, type: bug
