### ISSUE TITLE
Export time profile analysis change the units

### ISSUE THREAD

**Issue by AyaSaleh90** [Open-Systems-Pharmacology/PK-Sim#1640] opened 2021-02-05 14:52 UTC
Hello,
Whenever I export a simulated time profile analysis to an excel file so I can plot in R, it change the units of the concentration from pg/mL to umol/L for the the simulated profile,, while for the observed data it still the same (pg/mL)

is there a possible way when I export a simulated time profile analysis to excel file to keep the same units?
 ''Note: I have already set my default units in the manager user display units for concentration (mass) "

Thanks in advance

**Comment by msevestre** [comment] 2021-02-05 14:59
Hi @AyaSaleh90 
How do you export the values to excel? can you show us the function that you are using?

**Comment by AyaSaleh90** [comment] 2021-02-05 15:03
Hi @msevestre, I export it from PK-Sim itself as you can see from this pix
![Untitled](https://user-images.githubusercontent.com/67606842/107050548-a6d60d00-67cb-11eb-9f0e-6cde8f5ec3b6.png)

**Comment by msevestre** [comment] 2021-02-05 15:08
@AyaSaleh90 Interesting. This looks like a bug to me. 
We'll have to investigate

**Comment by msevestre** [comment] 2021-03-04 20:23
I can reproduce the issue in v10

**Comment by msevestre** [comment] 2021-03-04 21:34
@AyaSaleh90 For now, an easy fix is simply to change any property of the axis (grid line et.c.) This will update the underlying graph and exporting to excel should use the right unit. 
This will be fixed in the upcoming v10 verison

**Closed** 2021-03-04 22:05 UTC
Labels: type: bug

**Comment by AyaSaleh90** [comment] 2021-03-05 09:35
> @AyaSaleh90 For now, an easy fix is simply to change any property of the axis (grid line et.c.) This will update the underlying graph and exporting to excel should use the right unit.
> This will be fixed in the upcoming v10 verison

Many Thanks

**Comment by finattig** [comment] 2022-11-12 23:12
I am having the same problem even when I change the axis scale before the simulation and then export the results to CSV. It seems that the plasma concentration unit in the Excel output file is always generated in umol/L. I tried changing the unit in Utilities > Options > Display Units and it didn't work either. When I export the summary of the PK results (Show PK-Analysis > Export to excel, within the PK summary tab) it works.
