### ISSUE TITLE
Presentation logging does not work anymore in PKSim

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1543] opened 2020-08-05 16:00 UTC
Loading a project from snapshot, I should see some information in the presentation view
It worked in v9.1. After updating the logging logic, it does not work anymore

Steps to reproduce. 
Start PKSim
Load  a snapshot (ask @PavelBal  for one) (File=>Load from snapshot)
Click Start Import 

The log view remains empty

This is a v10 only bug

**Comment by msevestre** [comment] 2020-08-05 16:00
![image](https://user-images.githubusercontent.com/1041237/89435759-4a5a3e00-d713-11ea-8dc9-8c3338e87e6a.png)

**Comment by msevestre** [comment] 2020-09-03 00:39
Tried again. Same behavior
![image](https://user-images.githubusercontent.com/1041237/92055441-565e0d80-ed5c-11ea-97e9-44f648087eed.png)

**Comment by msevestre** [comment] 2020-09-03 00:39
This is happening in debug more (e.g in visual studio) as well

**Comment by msevestre** [comment] 2020-09-03 00:43
@abdelr @georgeDaskalakis 
I put a bunch of breakpoints in the PresenterLogger and they are never hit
![image](https://user-images.githubusercontent.com/1041237/92057329-e734e900-ed5c-11ea-9d7e-1bb68a75442e.png)

**Comment by msevestre** [comment] 2020-09-03 00:45
and that's definitely being called during init. 
![image](https://user-images.githubusercontent.com/1041237/92058309-3549ec80-ed5d-11ea-8b1a-695dfb94e759.png)

Not sure what's going on. Happy to debug with you

**Comment by abdelr** [comment] 2020-09-03 14:46
@msevestre  @georgeDaskalakis  I was able to reproduce too... and we have found the source of the problem... working on how to fix though...

**Comment by msevestre** [comment] 2020-09-03 15:08
How did you get it to work on your code? What was the difference?

**Comment by abdelr** [comment] 2020-09-03 18:29
I was checking develop branch, but I tried now on the Remove_Warning branch and there I see the behavior you described

**Comment by msevestre** [comment] 2020-09-03 18:32
Hum this is very weird. That branch has been merged into develop. Did you pull the latest develop?

**Comment by abdelr** [comment] 2020-09-03 18:44
I think I did... but I am not sure now... maybe it is more complicated than that... maybe it has to do with the fact that we used a forked branch meaning I have two physical repositories in my hdd... Anyway. The problem is that when you configure the LoggerCreator with 
```
         loggerCreator
            .AddLoggingBuilderConfiguration(builder =>
               builder
                  .SetMinimumLevel(LogLevel.Information)
                  .AddDebug()
                  .AddConsole()
            );

```
you work on an instance and when you use the logger at OSPLogger
```
var logger = _loggerCreator.GetOrCreateLogger(string.IsNullOrEmpty(categoryName) ? DEFAULT_LOGGER_CATEGORY : categoryName);
```
Meaning the configuration is then lost. I do not know why this is happening though. We register at InfrastructureRegister like this:
```
         var loggerCreator = new LoggerCreator();
         container.RegisterImplementationOf((ILoggerCreator)loggerCreator);
         container.Register<IOSPLogger, OSPLogger>(LifeStyle.Singleton);
```
and I also tried using the Register with the Singleton option for the LoggerCreator but still, I receive a different instance. I do not know why it is not working as a singleton. Do you have any idea here?

**Comment by msevestre** [comment] 2020-09-03 18:54
Are you `sure` that you are getting multiple instances? We are using this construct everywhere in the app...

**Comment by abdelr** [comment] 2020-09-03 18:56
I could show you... I might be wrong... and tired... but I am pretty sure

**Comment by abdelr** [comment] 2020-09-03 19:02
Maybe we could have a look together on Monday's meeting. Two persons should be able to detect the problem easier. Specially since I am now biased with what I think. I could be nice to have a spare pair of eyes ;)

**Comment by msevestre** [comment] 2020-09-03 19:08
I think it's because you register it also with convention
```
    container.AddScanner(scan =>
         {
            scan.AssemblyContainingType<InfrastructureRegister>();
            scan.WithConvention(new OSPSuiteRegistrationConvention(registerConcreteType: true));
            scan.ExcludeType<OSPLogger>();
         });

```

**Comment by msevestre** [comment] 2020-09-03 19:08
In this case, everything will be registered as transcient expect OSPLogger. If you want `LoggerCreator` to be singleton, you need to add  ` scan.ExcludeType<LoggerCreator>();`

**Comment by abdelr** [comment] 2020-09-03 20:05
You are definitely right. I did not notice this. I would have expected the Container to complain btw since we are registering two ways to resolve for a single interface but I guess since they are not the same it passed.
Thanks. I will commit the change. Should I do it on the old branch? It is already merged right? I test locally and it works so just let me know where to push.

**Comment by msevestre** [comment] 2020-09-03 20:17
not on the old branch.

Create a new branch fix it and create a PRSee https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/GIT_WORKFLOW.md#use-case-implementing-task-426-it-should-be-possible-to-delete-observed-data
so something like

```
git checkout -b 1543-logging-does-not-work
...fix...commit.
git push upstream 1543-logging-does-not-work
create PR
```

**Closed** 2021-03-05 14:21 UTC
Labels: type: bug
