### ISSUE TITLE
Population approach changes observed data of parent drug

### ISSUE THREAD

**Issue by Rubilu** [Open-Systems-Pharmacology/PK-Sim#1205] opened 2019-04-24 08:39 UTC
Hello everyone,

I've updated to 7.4 and in my population approach, the software changes the observed data - but only when I choose the parent drug. The metabolite data is correct.
For example: The cmax of the observed data is 65,26 µg/L with a standard deviation of 4,46. The simulation changes it into a cmax of 61,96 µg/L with a SD of 4,2. The metabolite cmax is identical in the simulation. When I take the same values for my parent drug but characterize them as values for the metabolite, the values are the same in the population approach. So, it seems to be a problem with the linking between parent drug and observed data.
I don't know how to fix this bug and hope that someone can help me.

Kind regards

**Comment by msevestre** [comment] 2019-04-24 11:52
Issue moved to PKSim
@rubilu: the title of the issue says 'oops something went wrong'
What does it have to do with this issue? Did you receive an error message?

Please attach a project and steps to reproduce the issue as I am not sure I understand what's the problem is.

**Comment by msevestre** [comment] 2019-04-24 11:57
Are you also suggesting that this bug is NEW? You are mentioning something about updating to 7.4

And are you in PKSim or MoBi?

Observed data should use the molweight of the associated drug.

IN which unit did you import them?

**Comment by msevestre** [comment] 2019-04-24 12:58
Thanks @Rubilu Can you attach the project to the issue? We could give it a quick look and let you know what's goin gon

**Comment by Rubilu** [comment] 2019-04-24 15:08
Here is an example project. 
Thank you for your help.

[Test.pksim5.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/3112905/Test.pksim5.zip)

**Comment by msevestre** [comment] 2019-04-24 18:11
your zip file only contains a shortcut to your project file. Can you upload the actual project file?

**Comment by Rubilu** [comment] 2019-04-25 11:13
I tried to upload the actual project file but the forum does not support pksim5 files.

**Comment by StephanSchaller** [comment] 2019-04-25 11:41
You have to zip it first. Forum supports Zip files.

**Comment by msevestre** [comment] 2019-04-30 17:05
@Rubilu Without the file, we will not be able to reproduce the issue and thus correct it
SImply go on your pksim file, zip it and attach it to this entry

**Comment by msevestre** [comment] 2019-06-13 16:29
@Rubilu Closing since you did not provide us with any file so that we could reproduce the issue.
Please reopen if you can attach the required info. THanks

**Closed by msevestre** 2019-06-13 16:29 UTC
Labels: feedback required
