### ISSUE TITLE
PK SIM crashed

### ISSUE THREAD

**Issue by harishkaushikbugworks** [Open-Systems-Pharmacology/PK-Sim#1188] opened 2019-04-16 16:28 UTC
<img width="960" alt="issue" src="https://user-images.githubusercontent.com/49284633/56227216-91da3800-6092-11e9-9f00-8b8d3b7f44d5.png">
Hello all of sudden my PK sim crashed and iam unabel to run,save or open any project
i have attched screen shot

Application:
PK-Sim® 7.4.0.127

The type initializer for 'NHibernate.Cfg.Configuration' threw an exception.
-----------------------------------------------------
The type initializer for 'NHibernate.LoggerProvider' threw an exception.
-----------------------------------------------------
Unable to instantiate: NHibernate.Log4NetLoggerFactory
-----------------------------------------------------
Exception has been thrown by the target of an invocation.
-----------------------------------------------------
The type initializer for 'NHibernate.Log4NetLoggerFactory' threw an exception.
-----------------------------------------------------
Object reference not set to an instance of an object.

Stack trace:
```
at NHibernate.Log4NetLoggerFactory.GetGetLoggerMethodCall[TParameter]()
   at NHibernate.Log4NetLoggerFactory..cctor()
 --- End of inner exception stack trace ---
   at NHibernate.Log4NetLoggerFactory..ctor()
 --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at NHibernate.LoggerProvider.GetLoggerFactory(String nhibernateLoggerClass)
 --- End of inner exception stack trace ---
   at NHibernate.LoggerProvider.GetLoggerFactory(String nhibernateLoggerClass)
   at NHibernate.LoggerProvider..cctor()
 --- End of inner exception stack trace ---
   at NHibernate.LoggerProvider.LoggerFor(Type type)
   at NHibernate.Cfg.Configuration..cctor()
 --- End of inner exception stack trace ---
   at NHibernate.Cfg.Configuration.Reset()
   at PKSim.Infrastructure.Services.SessionFactoryProvider.createSqlLiteConfigurationFor(String dataSource)
   at PKSim.Infrastructure.Services.SessionFactoryProvider.OpenSessionFactoryFor(String dataSource)
   at OSPSuite.Infrastructure.Services.SessionManager.OpenFactoryFor(String fileName)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(IWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass16_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass32_0.<openProjectFromFile>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment] 2019-04-16 19:44
@harishkaushikbugworks What has changed since the last time you could save the application?
Assuming here, that this not linked to PK-Sim if it worked before but more to something that has changed on your configuration (OS, Update etc..)

You could try to repair the installation, restart your computer, see what patch were applied etc..

**Comment by msevestre** [comment] 2019-04-16 19:47
Actually this is a duplicate of 
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1069#issuecomment-454553678

Please follow the instructions provided there

**Comment by msevestre** [comment] 2019-04-16 19:48
duplicates #1069 with workaround provided

**Closed by msevestre** 2019-04-16 19:48 UTC

**Comment by harishkaushikbugworks** [comment] 2019-04-17 05:00
Hello Msevestre
I did do what u said, i uninstalled entire setup and reinstalled the same, but nothing worked and same error pops up, when i tried to open the old file

Regards
Harish

**Comment by msevestre** [comment] 2019-04-17 11:39
The issue resolution that I linked didn't suggest to uninstall everything. Instead it suggested to copy a specific file into the installation folder.
If you follow this suggestion, the software will work again.

**Comment by harishkaushikbugworks** [comment] 2019-04-17 12:12
Hello Sevestre,
I did try to copy dll files even then it didn’t work, so on further exploring the forum found the portable PKSIM and Mobi
So installed those, now iam using those files

Is there any other way around let me know


Thanks & Regards

Harish Kaushik Kotakonda
Principal Scientist-DMPK

[logo]
Mob: +91 9550288659
www.bugworksresearch.com<http://www.bugworksresearch.com/>

**Comment by msevestre** [comment] 2019-04-17 12:19
@harishkaushikbugworks Copying the log4net.dll in the installation folder of PK-Sim should work (this is the only difference between the portable install and the official install. We added this file to the package)

Please confirm that this is what you did? Also please confirm where you copied the file (it should be in the PKSim installation folder)

**Comment by harishkaushikbugworks** [comment] 2019-04-17 12:26
Yes I did the same what you suggested below
I copied those files in the PK sim installation folder


Thanks & Regards

Harish Kaushik Kotakonda
Principal Scientist-DMPK

[logo]
Mob: +91 9550288659
www.bugworksresearch.com<http://www.bugworksresearch.com/>

**Comment by msevestre** [comment] 2019-04-17 12:27
@harishkaushikbugworks Would you mean pasting here the path of the installation folder? (path on your machine)

**Comment by harishkaushikbugworks** [comment] 2019-04-17 12:29
I have deleted the setup completely now and I have installed both portable PK SIM and Mobi separately, which now are working well


Thanks & Regards

Harish Kaushik Kotakonda
Principal Scientist-DMPK

[logo]
Mob: +91 9550288659
www.bugworksresearch.com<http://www.bugworksresearch.com/>
