### ISSUE TITLE
Database expression information is discarded in nightly biuld with new functionality

### ISSUE THREAD

**Issue by JanSchlender** [Open-Systems-Pharmacology/PK-Sim#1607] opened 2020-11-30 09:11 UTC
The introduced functionality for vizualisation of expression profiles allows filtered view on different organs/tissues/compartments. However, when a compartment with expression is selected to be hidden, its absolute, normalized and related expression to other compartments is discarded and cannot be retrieved by reselection.

**Comment by StephanSchaller** [comment] 2020-11-30 10:12
Already testing the new Expression Interface?

**Comment by JanSchlender** [comment] 2020-11-30 10:23
Can't wait

**Comment by msevestre** [comment] 2020-11-30 13:09
Can you put some screenshots? I am having some issues understanding what is filtered? Thanks @JanSchlender

**Comment by JanSchlender** [comment] 2020-11-30 13:39
Attached please find two screenshots. The first is the default CYP3A4 expression window including its localisation selection panel. In the second screenshot, I selected the vascular endothelium endosome. Deselecting one or both locations trigger a reset notification. However, only in case of the "intracellular" location, the parameters seem to be reset. 
![1](https://user-images.githubusercontent.com/26056951/100616718-ca875d80-3319-11eb-8642-999cda6eee0d.JPG)
![2](https://user-images.githubusercontent.com/26056951/100616730-cd824e00-3319-11eb-8ced-aeed7d4177dd.JPG)

**Comment by msevestre** [comment] 2020-11-30 16:36
Hum, I am probably not understanding the issue. Sorry about being so hard to work with :)

* If nothing is selected, you only have the rel exp in plasma
* If you select endothelium only, you have to specify the fraction endosome
* if you select the 3 locations, you have 3 fractions parameters where the sum should be 1

![image](https://user-images.githubusercontent.com/1041237/100636761-0a414b80-3300-11eb-908c-1a81e89784b9.png)

fraction expressed baso is readonly = 1- f_exp_endo - f_Exp_apical

If I select deselect, relevant parameters are added or hidden.
I think it behaved as expected. 

Can you please explain what should happen and is not happening? /cc @Yuri05 who might be able to enlighten me

**Comment by msevestre** [comment] 2020-12-03 14:54
@Yuri05 Bug or feature?

**Comment by Yuri05** [comment] 2020-12-04 16:55
Originally:
<img width="450" src="https://user-images.githubusercontent.com/25061876/101190785-296e0f00-3659-11eb-93df-718c24e38a38.png">
After changing of fractions and relExp:
<img width="450" src="https://user-images.githubusercontent.com/25061876/101190618-e613a080-3658-11eb-87ac-27f08d1b9281.png">
After deactivating of all VascEndo-Options and activating them again:
<img width="450" src="https://user-images.githubusercontent.com/25061876/101191357-dcd70380-3659-11eb-90c2-777479439f03.png">

Don't see any problem here.

**Comment by msevestre** [comment] 2020-12-04 22:07
Well the relexp is set to 0. Maybe this is an issue no?

**Comment by Yuri05** [comment] 2020-12-04 22:48
no, this is exactly as expected. if all options (e.g. all vascemdo in the example above) are deactivated, then the corresponding relexp are set to 0. So I don't know where the issue is and hope @JanSchlender can explain in more detail.

**Comment by msevestre** [comment] 2020-12-10 16:25
Jan closed it and I reopened it. Let's close it then :)

**Closed by msevestre** 2020-12-10 16:25 UTC
Labels: feedback required
