### ISSUE TITLE
Metabolite name is lost after process type change

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#604] opened 2018-04-13 07:45 UTC
To reproduce, 
1. open a new project in PK-Sim
2. Load the compound "Caffeine" from the templates. Alternatively, any existing project with at least one compound may be used.
3. Open "Caffeine" for edit, click on the ADME tab, then on CYP1A2 under "Metabolizing Enzymes".
4. Add a new process from the context menu (right-click) of CYP1A2.
5. In the dialogue window, enter data source and then the metabolite name.
6. After that, change the process type to something else, e.g., to "In vitro clearance - First Order".
7. Click on "Ok", then examine the newly created process. Note that the "Metabolite" field is empty.

This will not happen if the process type is selected before entering the metabolite name. Its just a minor nuisance since the metabolite name can be entered again.

**Comment by msevestre** [comment] 2018-04-18 20:15
This is a duplicate of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/529 which was fixed in 7.3

**Closed** 2018-04-18 20:16 UTC
Labels: duplicate
