### ISSUE TITLE
Error after re-configuring a rabbit-simulation after saving

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/PK-Sim#180] opened 2017-05-23 09:29 UTC
I have created 3 different rabbit simulations and saved the Pksim file. I cannot 'configure' the simulations anymore, it gives an error ('Array cannot be null. Parameter name: bytes').

![error](https://cloud.githubusercontent.com/assets/25530079/26347724/bc69ce24-3faa-11e7-84d9-c60404478458.png)

[Rabbit_Test_Paracetamol.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1021636/Rabbit_Test_Paracetamol.zip)

**Comment by Incei** [comment] 2017-05-23 10:54
It seems I can not create a new simulation either anymore.

**Comment by Yuri05** [comment] 2017-05-23 11:29
The problem is that the individual **_Rabbit_** cannot be loaded anymore

**Comment by Yuri05** [comment] 2017-05-23 11:52
Seems to be a problem during project saving.

I cannot reproduce this issue following all the steps in history made by @Incei (starting with the project attached)
[Rabbit_Test_Paracetamol.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1022016/Rabbit_Test_Paracetamol.zip)

**Comment by msevestre** [comment] 2017-05-23 11:57
Was it on a VM? My experience is that most problem we have we corrupted
project are because of some IO issues

**Comment by Incei** [comment] 2017-05-23 11:59
It was on the external PC via desktop connection.

**Comment by msevestre** [comment] 2017-05-23 12:33
What is the externalPC?

**Comment by msevestre** [comment] 2017-05-23 13:20
Cannot reproduce either
@Yuri05. How do you want to proceed?

**Comment by Yuri05** [comment] 2017-05-23 13:28
Let's close it for the moment. Seems to be a one time problem (closed remote session during saving or smthg like that?)

**Comment by msevestre** [comment] 2017-05-23 13:29
Let's create  a tag

**Closed** 2017-05-23 13:30 UTC
Labels: prio: high, type: bug, unable to reproduce
