### ISSUE TITLE
Buggy behaviour in PI: Id 54T2oOieckOeos4KB4QLQA not unique 

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1299] opened 2019-07-26 15:01 UTC
As discussed in earlier entries (e.g. #1109), I often face issues during the model development process when running PIs, changing the model structure, renaming simulations, deleting parameters etc. Typically, the PI can't be re-opened anymore or the results are lost. 

Attached is a sharable example: When opening the Id, the Error pasted below is thrown, but the PI can be opened nonetheless. 
When trying to run it the following error is displayed: 

![Error](https://user-images.githubusercontent.com/26541603/61960559-ff68ff00-afc5-11e9-9e47-9f7d5f1a8730.png)

Even more interestingly, when I delete a parameter from the list of identification parameters, a couple of other parameters are suddenly displayed in this list (which is reproducible in the attached file):

![Error2](https://user-images.githubusercontent.com/26541603/61960890-b796a780-afc6-11e9-8185-7a91ba30d3e8.png)

[PI-bug.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/3436282/PI-bug.zip)

Application:
PK-Sim® 8.0.22

Id 54T2oOieckOeos4KB4QLQA not unique

Stack trace:
```
at OSPSuite.Core.Domain.WithIdRepository.Register(IWithId objectWithId)
   at OSPSuite.Core.Serialization.Xml.SerializationContext.Register(IWithId withId)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.Xml.Serializers.PKSimParameterBaseXmlSerializer`1.TypedDeserialize(T parameter, XElement parameterElement, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.Xml.Serializers.PKSimParameterXmlSerializer.TypedDeserialize(PKSimParameter parameter, XElement parameterElement, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Core.Serialization.Xml.ParameterIdentificationXmlSerializer.TypedDeserialize(ParameterIdentification parameterIdentification, XElement parameterIdentificationElement, SerializationContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(Object objectToDeserialize, XElement outputToDeserialize, TContext context)
   at PKSim.Infrastructure.Serialization.Xml.XmlReader`1.ReadFrom(T objectToRead, XElement element, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Services.ParameterIdentificationContentLoader.LoadContentFor(ParameterIdentification parameterIdentification)
   at PKSim.Infrastructure.Services.LazyLoadTask.Load[TObject](TObject objectToLoad)
   at PKSim.Core.ExecutionContext.Load(ILazyLoadable lazyLoadable)
   at PKSim.Core.ExecutionContext.Load(IObjectBase objectBase)
   at OSPSuite.Presentation.UICommands.RenameObjectBaseUICommand`1.loadSubjectBeforeRenaming()
   at OSPSuite.Presentation.UICommands.RenameObjectBaseUICommand`1.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment] 2019-07-28 15:05
The stack trace mentions something about `Renaming`. Can you explain what you were doing? 

A step by step instruction on how to reproduce the bug would be great. The attached project is already corrupted so it's hard to understand what is happening

**Comment by AndreDlm** [comment] 2019-07-29 08:44
I've been working on this project for weeks, going one step back and two ahead, so a step by step instruction is difficult to give. 
What I did is to rename simulations, PIs, default parameters in the `Molecule BB` and observed data, re-configured simulations that were present in the PI (such as setting other defaults for `P_int`, `P_org` and `Solubility`) and added/deleted CL processes in the model. 
If it helps, I can sent you the full file including all simulations, PIs (not just the buggy one) and history.

**Comment by msevestre** [comment] 2019-07-30 17:08
probably linked to 
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/497

Hard to tell without steps to reproduce.

**Comment by msevestre** [comment] 2020-02-10 22:01
@AndreDlm Ok I have tried and cannot reproduce the issue. Let's keep it open for now and see if there is a way to reproduce it with a minimal example. It's there, but if I can't reproduce, I can't fix it

Maybe you could try on a simple project and see if you manage to reproduce it?

**Comment by msevestre** [comment] 2021-03-04 19:28
still can't reproduce .Closing for now

**Closed by msevestre** 2021-03-04 19:28 UTC
Labels: feedback required, type: bug
