### ISSUE TITLE
Observed data matching gets doubled in a cloned simulation

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/PK-Sim#2869] opened 2024-02-16 09:06 UTC
After cloning a simulation, the data matching in the Observed Data tab gets doubled in the cloned simulation (PK-Sim 11.2). See screenshot below.
This causes trouble if one wants to start a PI with a cloned simulation.

<img width="523" alt="image" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/26439150/fea65ad6-9dc6-4feb-ad9d-8e96d510e6bc">

**Comment by Yuri05** [comment] 2024-02-20 10:51
Known issue, fixed in upcoming version 12
Duplicate of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2592

**Closed by Yuri05** 2024-02-20 10:51 UTC
