### ISSUE TITLE
Creating individuals: No change of weight/height when setting up another age

### ISSUE THREAD

**Issue by edschm** [Open-Systems-Pharmacology/PK-Sim#157] opened 2017-05-16 16:27 UTC
PK-Sim v. 7.0.0, build 8197

When selecting an age other than those of the standard individual, weight and height remain unchanged yet anatomical and physiological properties such as organ volumes or blood flow rates are altered. However, the specific GFR is still unchanged.

[Biometrics_ES.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1005169/Biometrics_ES.zip)

**Comment by msevestre** [comment] 2017-05-16 16:48
@edschm Input of age value does not automatically update default weight and height. Instead you need to click on the `MEAN` button which retrieves the mean Weight and Height values for the selected population and age. 

Does it solve the problem you are describing ?

**Comment by edschm** [comment] 2017-05-16 17:10
@msevestre Unfortunately, the mean weight and height values still remain the same (73 kg, 176 cm, when selecting the 'European' population), regardless of the age.

**Comment by msevestre** [comment] 2017-05-16 17:14
@edschm Interesting...

**Comment by msevestre** [comment] 2017-05-16 18:51
@edschm I can reproduce the issue with version 7.0.0
However this is by design as the original ICRP data only contain values up to 30 years of age.

The good news is that the issue is fixed in the upcoming 7.1.0 (see https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/32) based on the publication http://dx.doi.org/10.1007/s40262-016-0422-3

The version is in beta now and will be officially released soon

**Closed** 2017-05-16 18:51 UTC
Labels: question
