### ISSUE TITLE
Add predicted vs observed data plot in individual simulation

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#441] opened 2017-11-09 17:05 UTC
It's quite useful to be able to compare predicted vs observed data. We have the ability to get such a plot when optimizing a simulation. Why not make it a standard plot for Individual Simulation?

**Comment by Yuri05** [comment] 2021-08-10 15:11
duplicate of #306

**Closed by Yuri05** 2021-08-10 15:11 UTC
Labels: type: feature
