### ISSUE TITLE
Parameter Identification: Add the possibility to export the optimized parameter values into a new simulation

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1381] opened 2020-01-15 20:46 UTC
At the moment, it is possible to transfer the optimal values into an existing simulation. However, it could  be useful to create a clone of the optimized simulation where the optimized parameter values would be set. That way, it would be very easy to compare various optimization results

**Comment by Yuri05** [comment] 2021-08-11 15:54
duplicate of #1055

**Closed by Yuri05** 2021-08-11 15:54 UTC
Labels: type: feature
