### ISSUE TITLE
Observed data export crash

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1527] opened 2020-07-16 14:58 UTC
[ExportCrash.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/4932235/ExportCrash.zip)
When exporting observed data to Excel:

```
Application:
PK-Sim® 9.0.170

InvalidSheetName

Stack trace:
at l7.d(String A_0)
   at l7.b(String A_0)
   at l7.e(String A_0)
   at re.a(Int32 A_0, String A_1)
   at OSPSuite.Infrastructure.Export.ExportToExcelTask.exportDataTableToWorkBook(WorkBook workBook, DataTable dataTable, Int32 sheetIndex)
   at OSPSuite.Infrastructure.Export.ExportToExcelTask.ExportDataTablesToExcel(IEnumerable`1 dataTables, String fileName, Boolean openExcel, Action`2 workbookConfiguration)
   at OSPSuite.Infrastructure.Export.ExportToExcelTask.ExportDataTablesToExcel(IEnumerable`1 dataTables, String fileName, Boolean openExcel, Action`1 workbookConfiguration)
   at OSPSuite.Infrastructure.Export.DataRepositoryExportTask.ExportToExcel(IEnumerable`1 dataTables, String fileName, Boolean launchExcel)
   at OSPSuite.Infrastructure.Export.DataRepositoryExportTask.ExportToExcel(IEnumerable`1 dataColumns, String fileName, Boolean launchExcel, DataColumnExportOptions exportOptions)
   at OSPSuite.Core.Domain.Services.ObservedDataTask.Export(DataRepository observedData)
   at OSPSuite.Presentation.UICommands.ExportObservedDataToExcelCommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment] 2020-07-16 14:58
@Incei FYI

**Comment by msevestre** [comment] 2020-07-16 15:00
duplicate of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1494 ?

**Comment by Yuri05** [comment] 2020-07-16 15:05
could be.

**Comment by Yuri05** [comment] 2021-07-05 09:11
@abdelr @georgeDaskalakis Just tried it with PK-Sim 10: still crashes, now with the error message
```
Application:
PK-Sim® 10.0.170

Invalid sheet name 'Digoxin, 0.5 mg colon, Ochs ''. Sheet names must not begin or end with (').

Stack trace:

at NPOI.SS.Util.WorkbookUtil.ValidateSheetName(String sheetName)
   at NPOI.XSSF.UserModel.XSSFWorkbook.CreateSheet(String sheetname)
   at OSPSuite.Infrastructure.Export.ExportToExcelTask.exportDataTableToWorkBook(IWorkbookConfiguration workBookConfiguration, DataTable dataTable)
   at OSPSuite.Infrastructure.Export.ExportToExcelTask.ExportDataTablesToExcel(IEnumerable`1 dataTables, String fileName, Boolean openExcel, IWorkbookConfiguration workBookConfiguration)
   at OSPSuite.Infrastructure.Export.DataRepositoryExportTask.ExportToExcel(IEnumerable`1 dataTables, String fileName, Boolean launchExcel)
   at OSPSuite.Infrastructure.Export.DataRepositoryExportTask.ExportToExcel(IEnumerable`1 dataColumns, String fileName, Boolean launchExcel, DataColumnExportOptions exportOptions)
   at OSPSuite.Core.Domain.Services.ObservedDataTask.Export(DataRepository observedData)
   at OSPSuite.Presentation.UICommands.ExportObservedDataToExcelCommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by georgeDaskalakis** [comment] 2021-07-05 19:52
The problem here is the single quote character ( ' ) in the name of the observed data set in exactly the 30th position. The maximum allowed name dor the sheet is 29 characters, then the name of the sheet ends up having a ' at the end, which is not accepted by excel. I have added a cleaning up of any ' characters left at the beginning or in the end of the name ater the truncation.

**Comment by georgeDaskalakis** [comment] 2021-07-05 19:55
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1158](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1158) via [**ZenHub**](https://www.zenhub.com/)

**Closed by georgeDaskalakis** 2021-07-05 19:55 UTC
Labels: subsystem: import & export, type: bug
