### ISSUE TITLE
Parameters in parameter identifications (PK-Sim) cannot be deleted

### ISSUE THREAD

**Issue by lkuepfer** [Open-Systems-Pharmacology/PK-Sim#1258] opened 2019-05-22 14:38 UTC
Identification parameters cannot be deleted since icon is missing in row

**Comment by msevestre** [comment] 2019-05-22 15:20
@lkuepfer Cannot reproduce
![image](https://user-images.githubusercontent.com/1041237/58186734-77900d00-7c83-11e9-925c-c5db30d8104d.png)

What skin are you using?
Also do you have some special font settings such as font scaling etc?

@Yuri05 Can you reproduce the issue?

**Comment by lkuepfer** [comment] 2019-05-22 19:48
Several skins were tested, this not resolve the issue.
I am using Windows X, Resolution 3860x2140 (250%).
All settings are default. 

The problem does NOT occur in MoBi!

**Comment by msevestre** [comment] 2019-05-22 20:08
ok can you try with v8?
http://pk-sim-portable.open-systems-pharmacology.org

downlaod the zip file, dezip and start pksim. I think it should be solved
that way

**Comment by msevestre** [comment] 2019-06-12 09:24
@lkuepfer Can you let me know if the issue is fixed with the v8?

**Comment by Yuri05** [comment] 2020-02-10 14:42
@lkuepfer Can you check please if the issue is fixed in v8?

**Comment by Yuri05** [comment] 2021-08-11 14:42
closing due to inactivity

**Closed by Yuri05** 2021-08-11 14:42 UTC
Labels: type: bug, subsystem: UI, unable to reproduce, feedback required
