### ISSUE TITLE
Expression in zonated/unzonated livers

### ISSUE THREAD

**Issue by lkuepfer** [Open-Systems-Pharmacology/PK-Sim#222] opened 2017-06-12 21:23 UTC
Export of PK-Sim to Mobi and subsequent simulation building leads to a set of warning Messages ('liver|intracellular')

**Comment by lkuepfer** [comment] 2017-06-13 10:27
[LiverZonation_ProteinBinding_MoBi_Warnings.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1071049/LiverZonation_ProteinBinding_MoBi_Warnings.zip)

**Comment by msevestre** [comment] 2017-06-14 15:54
@lkuepfer 
Using the attached project when exporting to MoBi, I only see the following messages
![image](https://user-images.githubusercontent.com/1041237/27142125-23dc0fd2-50f8-11e7-92d8-2e0919fcd733.png)

There is nothing there regarding "Expression in zonated/unzonated livers". Are those messages the one you meant?

**Comment by msevestre** [comment] 2017-06-14 16:25
For those observers, the problem is that they are created in all liver zones without knowing if a molecule will be indeed available in the container. Best is too enhance the mechanism in MoBi to bypass validation for PK-Sim observers for those observer as well.

**Comment by msevestre** [comment] 2017-06-14 18:37
Fixes in MoBi. Those observers will be ignored

**Closed by msevestre** 2017-06-14 18:37 UTC
Labels: type: bug
