### ISSUE TITLE
An error occurred when calculating PK parameters for the population.

### ISSUE THREAD

**Issue by RoachWang** [Open-Systems-Pharmacology/PK-Sim#2830] opened 2023-11-13 11:21 UTC
Application:
PK-Sim® 11.2.142

Value cannot be null.
Parameter name: source

Stack trace:
```
at System.Linq.OrderedEnumerable`2..ctor(IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer, Boolean descending)
   at System.Linq.Enumerable.OrderBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at PKSim.Core.Mappers.ProtocolToSchemaItemsMapper.MapFrom(Protocol protocol)
   at PKSim.Presentation.Presenters.Simulations.GlobalPKAnalysisPresenter.<CanCalculateGlobalPK>b__33_0(Compound compound)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PKSim.Presentation.Presenters.Simulations.GlobalPKAnalysisPresenter.CanCalculateGlobalPK()
   at PKSim.Presentation.Presenters.Simulations.PopulationPKAnalysisPresenter.CalculatePKAnalyses(IPopulationDataCollector populationDataCollector, ChartData`2 timeProfileChartData, PopulationStatisticalAnalysis populationAnalysis)
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.calculatePKAnalysis()
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.showAnalysis()
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.setViewMode(Boolean shouldShowAnalysis)
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.SwitchPKAnalysisPlot()
   at PKSim.UI.Views.Charts.BasePKAnalysisWithChartView.switchPKAnalysis()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by Yuri05** [comment] 2024-03-01 13:50
Duplicate of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2632
Will be fixed in the next release

**Closed by Yuri05** 2024-03-01 13:50 UTC
Labels: type: bug
