### ISSUE TITLE
Unit conversion error

### ISSUE THREAD

**Issue by TheiBa** [Open-Systems-Pharmacology/PK-Sim#395] opened 2017-10-14 15:54 UTC
Compound parameter input for molecular weight can be given in kDa, which is then automatically converted to g/mol 1to1, which is wrong (1 g/mol = 1 Da = 0.001 kDa), i.e. kDa input should be multiplied by 1000 to get back to g/mol.

**Comment by msevestre** [comment] 2017-10-14 16:37
interesting that no one ever found out about that!

**Comment by msevestre** [comment] 2017-10-14 16:38
@Yuri05 this should be fixed in 7.2 IMO

**Comment by msevestre** [comment] 2017-10-16 12:28
@TheiBa I cannot reproduce the problem.
https://github.com/Open-Systems-Pharmacology/OSPSuite.Dimensions/blob/master/OSPSuite.Dimensions.xml#L483

Is the line where the conversion is being defined. There is a factor 1000 between kDa and g/mol

I think the issue is actually with the UI: There is no automatic conversion between unit in the program. Instead it's not possible to enter the value in the kDA

**Comment by msevestre** [comment] 2017-10-16 14:19
This has been fixed for 7.2

**Comment by TheiBa** [comment] 2017-10-16 14:25
So, now - cannot reproduce or fixed? Reproduction also not possible from within PK-Sim, if you select kda as unit for MW and then move to another field?

**Comment by msevestre** [comment] 2017-10-16 14:32
@TheiBa see above. The conversion factor is right. The problem is in the UI which I could reproduce and just fixed. Thanks

**Comment by TheiBa** [comment] 2017-10-16 14:37
Ok clear now, thanks for fixing

**Closed** 2017-10-19 14:36 UTC
Labels: effort: low (hours), prio: high, type: bug

**Comment by TheiBa** [comment] 2017-11-20 16:16
yep. works. looking at the options I wonder who requested the unit option kg/µmol, kg/mol is als unusual, but basically kDa, but kg/µmol, I wounder, anyway that is not a bug but a potentially unnecessary feature that does not hurt, so whatever ...

**Comment by Yuri05** [comment] 2017-11-20 17:27
kg/µmol is the internal unit for this dimension and currently all units are shown in the UI.
In the future we might hide some of them.

**Comment by msevestre** [comment] 2017-11-21 01:13
I think there is a flag "visible" for a unit no?
