### ISSUE TITLE
Feature request: save/transfer entire observed data tree between projects

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#858] opened 2018-06-20 12:40 UTC
We currently can transfer individual observed data sets into the template database and load it back from there. Also, we can save individual observed data sets to a PKML file for later MoBi import.

There are cases where a larger number of observed data sets pile up, and where they may be cleverly organized in a subfolder structure. It would be a useful feature to be able to transfer an entire subfolder tree between projects in the same way.

**Comment by msevestre** [comment] 2018-06-20 13:03
I like this idea a lot

**Comment by Yuri05** [comment] 2021-08-11 11:48
duplicate of #1053

**Closed by Yuri05** 2021-08-11 11:48 UTC
Labels: type: feature
