### ISSUE TITLE
UI issue: After adding a protein to an individual, the ontogeny plot can initially not be displayed

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1928] opened 2021-10-28 15:25 UTC
I cam across the following minor UI issue in v10: When adding a protein to an already existing individual, the plot showing the ontogeny function of the protein can initially not be displayed (the button is greyed out):
![image](https://user-images.githubusercontent.com/26541603/139286492-96b9b88a-dad0-4853-829d-14ae0f1f1e02.png)

Displaying it is possible by closing and re-opening the individual building block or by clicking on `Load ontogeny from file...` and canceling

**Comment by msevestre** [comment] 2021-11-01 20:56
@AndreDlm I can't reproduce....how do you do this exactly?

**Comment by AndreDlm** [comment] 2021-11-19 14:09
Just open PK-Sim, add an individual and load any protein from the database for which we have an ontogeny (e.g. CYP1A2, CYP3A4)

**Comment by msevestre** [comment] 2022-01-21 15:39
This is fixed with the current Expression Profile implementation

**Closed by msevestre** 2022-01-21 15:39 UTC
Labels: type: bug, subsystem: UI, feedback required
